FROM golang:1.19-buster as builder

WORKDIR /server
COPY go.* ./
RUN go mod download
COPY . .
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v -o application cmd/server/*

FROM alpine:3.15.4
WORKDIR /server
COPY --from=builder /server/application /server/application
COPY *.yaml ./
CMD ["/server/application"]