FROM golang:1.19-buster as builder

WORKDIR /client
COPY go.* ./
RUN go mod download
COPY . .
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v -o application cmd/client/*

FROM alpine:3.15.4
WORKDIR /client
COPY --from=builder /client/application /client/application
COPY *.yaml ./
CMD ["/client/application"]