// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: pkg/proto/mafia.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNKNOWN  Role = 0
	Role_ROLE_INNOCENT Role = 1
	Role_ROLE_SHERIFF  Role = 2
	Role_ROLE_MAFIOSI  Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNKNOWN",
		1: "ROLE_INNOCENT",
		2: "ROLE_SHERIFF",
		3: "ROLE_MAFIOSI",
	}
	Role_value = map[string]int32{
		"ROLE_UNKNOWN":  0,
		"ROLE_INNOCENT": 1,
		"ROLE_SHERIFF":  2,
		"ROLE_MAFIOSI":  3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_mafia_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_pkg_proto_mafia_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{0}
}

type Team int32

const (
	Team_TEAM_UNKNOWN   Team = 0
	Team_TEAM_CIVILIANS Team = 1
	Team_TEAM_MAFIA     Team = 2
)

// Enum value maps for Team.
var (
	Team_name = map[int32]string{
		0: "TEAM_UNKNOWN",
		1: "TEAM_CIVILIANS",
		2: "TEAM_MAFIA",
	}
	Team_value = map[string]int32{
		"TEAM_UNKNOWN":   0,
		"TEAM_CIVILIANS": 1,
		"TEAM_MAFIA":     2,
	}
)

func (x Team) Enum() *Team {
	p := new(Team)
	*p = x
	return p
}

func (x Team) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Team) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_mafia_proto_enumTypes[1].Descriptor()
}

func (Team) Type() protoreflect.EnumType {
	return &file_pkg_proto_mafia_proto_enumTypes[1]
}

func (x Team) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Team.Descriptor instead.
func (Team) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{1}
}

type GameEvent_Type int32

const (
	GameEvent_EVENT_UNKNOWN       GameEvent_Type = 0
	GameEvent_EVENT_PLAYER_JOINED GameEvent_Type = 1
	GameEvent_EVENT_PLAYER_LEFT   GameEvent_Type = 2
	GameEvent_EVENT_MESSAGE       GameEvent_Type = 3
	GameEvent_EVENT_GAME_STARTED  GameEvent_Type = 4
	GameEvent_EVENT_GAME_FINISHED GameEvent_Type = 5
	GameEvent_EVENT_DAY_STARTED   GameEvent_Type = 6
	GameEvent_EVENT_NIGHT_STARTED GameEvent_Type = 7
)

// Enum value maps for GameEvent_Type.
var (
	GameEvent_Type_name = map[int32]string{
		0: "EVENT_UNKNOWN",
		1: "EVENT_PLAYER_JOINED",
		2: "EVENT_PLAYER_LEFT",
		3: "EVENT_MESSAGE",
		4: "EVENT_GAME_STARTED",
		5: "EVENT_GAME_FINISHED",
		6: "EVENT_DAY_STARTED",
		7: "EVENT_NIGHT_STARTED",
	}
	GameEvent_Type_value = map[string]int32{
		"EVENT_UNKNOWN":       0,
		"EVENT_PLAYER_JOINED": 1,
		"EVENT_PLAYER_LEFT":   2,
		"EVENT_MESSAGE":       3,
		"EVENT_GAME_STARTED":  4,
		"EVENT_GAME_FINISHED": 5,
		"EVENT_DAY_STARTED":   6,
		"EVENT_NIGHT_STARTED": 7,
	}
)

func (x GameEvent_Type) Enum() *GameEvent_Type {
	p := new(GameEvent_Type)
	*p = x
	return p
}

func (x GameEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_mafia_proto_enumTypes[2].Descriptor()
}

func (GameEvent_Type) Type() protoreflect.EnumType {
	return &file_pkg_proto_mafia_proto_enumTypes[2]
}

func (x GameEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameEvent_Type.Descriptor instead.
func (GameEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{5, 0}
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Alive    bool   `protobuf:"varint,2,opt,name=alive,proto3" json:"alive,omitempty"`
	Role     *Role  `protobuf:"varint,3,opt,name=role,proto3,enum=mafia.Role,oneof" json:"role,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Player) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *Player) GetRole() Role {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return Role_ROLE_UNKNOWN
}

type VotePaper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Voter     *Player `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	Candidate *Player `protobuf:"bytes,2,opt,name=candidate,proto3,oneof" json:"candidate,omitempty"`
}

func (x *VotePaper) Reset() {
	*x = VotePaper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VotePaper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VotePaper) ProtoMessage() {}

func (x *VotePaper) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VotePaper.ProtoReflect.Descriptor instead.
func (*VotePaper) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{1}
}

func (x *VotePaper) GetVoter() *Player {
	if x != nil {
		return x.Voter
	}
	return nil
}

func (x *VotePaper) GetCandidate() *Player {
	if x != nil {
		return x.Candidate
	}
	return nil
}

type GetPlayersWithRolesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPlayersWithRolesRequest) Reset() {
	*x = GetPlayersWithRolesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayersWithRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayersWithRolesRequest) ProtoMessage() {}

func (x *GetPlayersWithRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayersWithRolesRequest.ProtoReflect.Descriptor instead.
func (*GetPlayersWithRolesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{2}
}

type GetPlayersWithRolesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *GetPlayersWithRolesResponse) Reset() {
	*x = GetPlayersWithRolesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayersWithRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayersWithRolesResponse) ProtoMessage() {}

func (x *GetPlayersWithRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayersWithRolesResponse.ProtoReflect.Descriptor instead.
func (*GetPlayersWithRolesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayersWithRolesResponse) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

// JoinGame Method
type JoinGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *JoinGameRequest) Reset() {
	*x = JoinGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRequest) ProtoMessage() {}

func (x *JoinGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRequest.ProtoReflect.Descriptor instead.
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{4}
}

func (x *JoinGameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GameEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type GameEvent_Type `protobuf:"varint,1,opt,name=type,proto3,enum=mafia.GameEvent_Type" json:"type,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*GameEvent_PayloadPlayerJoined_
	//	*GameEvent_PayloadPlayerLeft_
	//	*GameEvent_PayloadMessage_
	//	*GameEvent_PayloadGameStarted_
	//	*GameEvent_PayloadGameFinished_
	//	*GameEvent_PayloadDayStarted_
	//	*GameEvent_PayloadNightStarted_
	Payload isGameEvent_Payload `protobuf_oneof:"payload"`
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{5}
}

func (x *GameEvent) GetType() GameEvent_Type {
	if x != nil {
		return x.Type
	}
	return GameEvent_EVENT_UNKNOWN
}

func (m *GameEvent) GetPayload() isGameEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *GameEvent) GetPayloadPlayerJoined() *GameEvent_PayloadPlayerJoined {
	if x, ok := x.GetPayload().(*GameEvent_PayloadPlayerJoined_); ok {
		return x.PayloadPlayerJoined
	}
	return nil
}

func (x *GameEvent) GetPayloadPlayerLeft() *GameEvent_PayloadPlayerLeft {
	if x, ok := x.GetPayload().(*GameEvent_PayloadPlayerLeft_); ok {
		return x.PayloadPlayerLeft
	}
	return nil
}

func (x *GameEvent) GetPayloadMessage() *GameEvent_PayloadMessage {
	if x, ok := x.GetPayload().(*GameEvent_PayloadMessage_); ok {
		return x.PayloadMessage
	}
	return nil
}

func (x *GameEvent) GetPayloadGameStarted() *GameEvent_PayloadGameStarted {
	if x, ok := x.GetPayload().(*GameEvent_PayloadGameStarted_); ok {
		return x.PayloadGameStarted
	}
	return nil
}

func (x *GameEvent) GetPayloadGameFinished() *GameEvent_PayloadGameFinished {
	if x, ok := x.GetPayload().(*GameEvent_PayloadGameFinished_); ok {
		return x.PayloadGameFinished
	}
	return nil
}

func (x *GameEvent) GetPayloadDayStarted() *GameEvent_PayloadDayStarted {
	if x, ok := x.GetPayload().(*GameEvent_PayloadDayStarted_); ok {
		return x.PayloadDayStarted
	}
	return nil
}

func (x *GameEvent) GetPayloadNightStarted() *GameEvent_PayloadNightStarted {
	if x, ok := x.GetPayload().(*GameEvent_PayloadNightStarted_); ok {
		return x.PayloadNightStarted
	}
	return nil
}

type isGameEvent_Payload interface {
	isGameEvent_Payload()
}

type GameEvent_PayloadPlayerJoined_ struct {
	PayloadPlayerJoined *GameEvent_PayloadPlayerJoined `protobuf:"bytes,5,opt,name=payload_player_joined,json=payloadPlayerJoined,proto3,oneof"`
}

type GameEvent_PayloadPlayerLeft_ struct {
	PayloadPlayerLeft *GameEvent_PayloadPlayerLeft `protobuf:"bytes,6,opt,name=payload_player_left,json=payloadPlayerLeft,proto3,oneof"`
}

type GameEvent_PayloadMessage_ struct {
	PayloadMessage *GameEvent_PayloadMessage `protobuf:"bytes,7,opt,name=payload_message,json=payloadMessage,proto3,oneof"`
}

type GameEvent_PayloadGameStarted_ struct {
	PayloadGameStarted *GameEvent_PayloadGameStarted `protobuf:"bytes,8,opt,name=payload_game_started,json=payloadGameStarted,proto3,oneof"`
}

type GameEvent_PayloadGameFinished_ struct {
	PayloadGameFinished *GameEvent_PayloadGameFinished `protobuf:"bytes,9,opt,name=payload_game_finished,json=payloadGameFinished,proto3,oneof"`
}

type GameEvent_PayloadDayStarted_ struct {
	PayloadDayStarted *GameEvent_PayloadDayStarted `protobuf:"bytes,10,opt,name=payload_day_started,json=payloadDayStarted,proto3,oneof"`
}

type GameEvent_PayloadNightStarted_ struct {
	PayloadNightStarted *GameEvent_PayloadNightStarted `protobuf:"bytes,11,opt,name=payload_night_started,json=payloadNightStarted,proto3,oneof"`
}

func (*GameEvent_PayloadPlayerJoined_) isGameEvent_Payload() {}

func (*GameEvent_PayloadPlayerLeft_) isGameEvent_Payload() {}

func (*GameEvent_PayloadMessage_) isGameEvent_Payload() {}

func (*GameEvent_PayloadGameStarted_) isGameEvent_Payload() {}

func (*GameEvent_PayloadGameFinished_) isGameEvent_Payload() {}

func (*GameEvent_PayloadDayStarted_) isGameEvent_Payload() {}

func (*GameEvent_PayloadNightStarted_) isGameEvent_Payload() {}

// GetGameStatus Method
type GetGameStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetGameStatusRequest) Reset() {
	*x = GetGameStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStatusRequest) ProtoMessage() {}

func (x *GetGameStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStatusRequest.ProtoReflect.Descriptor instead.
func (*GetGameStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{6}
}

type GetGameStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Self    *Player   `protobuf:"bytes,2,opt,name=self,proto3" json:"self,omitempty"`
	Winners *Team     `protobuf:"varint,3,opt,name=winners,proto3,enum=mafia.Team,oneof" json:"winners,omitempty"`
}

func (x *GetGameStatusResponse) Reset() {
	*x = GetGameStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStatusResponse) ProtoMessage() {}

func (x *GetGameStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStatusResponse.ProtoReflect.Descriptor instead.
func (*GetGameStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{7}
}

func (x *GetGameStatusResponse) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GetGameStatusResponse) GetSelf() *Player {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *GetGameStatusResponse) GetWinners() Team {
	if x != nil && x.Winners != nil {
		return *x.Winners
	}
	return Team_TEAM_UNKNOWN
}

// SendMessage Method
type SendMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverCount uint64 `protobuf:"varint,1,opt,name=receiver_count,json=receiverCount,proto3" json:"receiver_count,omitempty"`
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{9}
}

func (x *SendMessageResponse) GetReceiverCount() uint64 {
	if x != nil {
		return x.ReceiverCount
	}
	return 0
}

// Kick Method
type KickRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *KickRequest) Reset() {
	*x = KickRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickRequest) ProtoMessage() {}

func (x *KickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickRequest.ProtoReflect.Descriptor instead.
func (*KickRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{10}
}

func (x *KickRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type KickResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KickResponse) Reset() {
	*x = KickResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickResponse) ProtoMessage() {}

func (x *KickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickResponse.ProtoReflect.Descriptor instead.
func (*KickResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{11}
}

// Kill Method
type KillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{12}
}

func (x *KillRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type KillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{13}
}

// CheckTeam Method
type CheckTeamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *CheckTeamRequest) Reset() {
	*x = CheckTeamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeamRequest) ProtoMessage() {}

func (x *CheckTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeamRequest.ProtoReflect.Descriptor instead.
func (*CheckTeamRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{14}
}

func (x *CheckTeamRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CheckTeamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Team     Team   `protobuf:"varint,2,opt,name=team,proto3,enum=mafia.Team" json:"team,omitempty"`
}

func (x *CheckTeamResponse) Reset() {
	*x = CheckTeamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTeamResponse) ProtoMessage() {}

func (x *CheckTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTeamResponse.ProtoReflect.Descriptor instead.
func (*CheckTeamResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{15}
}

func (x *CheckTeamResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CheckTeamResponse) GetTeam() Team {
	if x != nil {
		return x.Team
	}
	return Team_TEAM_UNKNOWN
}

type GameEvent_PayloadPlayerJoined struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *GameEvent_PayloadPlayerJoined) Reset() {
	*x = GameEvent_PayloadPlayerJoined{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameEvent_PayloadPlayerJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent_PayloadPlayerJoined) ProtoMessage() {}

func (x *GameEvent_PayloadPlayerJoined) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent_PayloadPlayerJoined.ProtoReflect.Descriptor instead.
func (*GameEvent_PayloadPlayerJoined) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GameEvent_PayloadPlayerJoined) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type GameEvent_PayloadPlayerLeft struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *GameEvent_PayloadPlayerLeft) Reset() {
	*x = GameEvent_PayloadPlayerLeft{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameEvent_PayloadPlayerLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent_PayloadPlayerLeft) ProtoMessage() {}

func (x *GameEvent_PayloadPlayerLeft) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent_PayloadPlayerLeft.ProtoReflect.Descriptor instead.
func (*GameEvent_PayloadPlayerLeft) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{5, 1}
}

func (x *GameEvent_PayloadPlayerLeft) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type GameEvent_PayloadMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender  *Player `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Content string  `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *GameEvent_PayloadMessage) Reset() {
	*x = GameEvent_PayloadMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameEvent_PayloadMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent_PayloadMessage) ProtoMessage() {}

func (x *GameEvent_PayloadMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent_PayloadMessage.ProtoReflect.Descriptor instead.
func (*GameEvent_PayloadMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{5, 2}
}

func (x *GameEvent_PayloadMessage) GetSender() *Player {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *GameEvent_PayloadMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GameEvent_PayloadGameStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Role    Role      `protobuf:"varint,2,opt,name=role,proto3,enum=mafia.Role" json:"role,omitempty"`
}

func (x *GameEvent_PayloadGameStarted) Reset() {
	*x = GameEvent_PayloadGameStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameEvent_PayloadGameStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent_PayloadGameStarted) ProtoMessage() {}

func (x *GameEvent_PayloadGameStarted) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent_PayloadGameStarted.ProtoReflect.Descriptor instead.
func (*GameEvent_PayloadGameStarted) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{5, 3}
}

func (x *GameEvent_PayloadGameStarted) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameEvent_PayloadGameStarted) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNKNOWN
}

type GameEvent_PayloadGameFinished struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Winners Team      `protobuf:"varint,1,opt,name=winners,proto3,enum=mafia.Team" json:"winners,omitempty"`
	Players []*Player `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *GameEvent_PayloadGameFinished) Reset() {
	*x = GameEvent_PayloadGameFinished{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameEvent_PayloadGameFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent_PayloadGameFinished) ProtoMessage() {}

func (x *GameEvent_PayloadGameFinished) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent_PayloadGameFinished.ProtoReflect.Descriptor instead.
func (*GameEvent_PayloadGameFinished) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{5, 4}
}

func (x *GameEvent_PayloadGameFinished) GetWinners() Team {
	if x != nil {
		return x.Winners
	}
	return Team_TEAM_UNKNOWN
}

func (x *GameEvent_PayloadGameFinished) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type GameEvent_PayloadDayStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DayId        uint64  `protobuf:"varint,1,opt,name=day_id,json=dayId,proto3" json:"day_id,omitempty"`
	KilledPlayer *Player `protobuf:"bytes,2,opt,name=killed_player,json=killedPlayer,proto3,oneof" json:"killed_player,omitempty"` // who was killed that night
}

func (x *GameEvent_PayloadDayStarted) Reset() {
	*x = GameEvent_PayloadDayStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameEvent_PayloadDayStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent_PayloadDayStarted) ProtoMessage() {}

func (x *GameEvent_PayloadDayStarted) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent_PayloadDayStarted.ProtoReflect.Descriptor instead.
func (*GameEvent_PayloadDayStarted) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{5, 5}
}

func (x *GameEvent_PayloadDayStarted) GetDayId() uint64 {
	if x != nil {
		return x.DayId
	}
	return 0
}

func (x *GameEvent_PayloadDayStarted) GetKilledPlayer() *Player {
	if x != nil {
		return x.KilledPlayer
	}
	return nil
}

type GameEvent_PayloadNightStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DayId        uint64       `protobuf:"varint,1,opt,name=day_id,json=dayId,proto3" json:"day_id,omitempty"`
	KickedPlayer *Player      `protobuf:"bytes,2,opt,name=kicked_player,json=kickedPlayer,proto3,oneof" json:"kicked_player,omitempty"` // who was killed that day
	Votes        []*VotePaper `protobuf:"bytes,3,rep,name=votes,proto3" json:"votes,omitempty"`
}

func (x *GameEvent_PayloadNightStarted) Reset() {
	*x = GameEvent_PayloadNightStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_mafia_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameEvent_PayloadNightStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent_PayloadNightStarted) ProtoMessage() {}

func (x *GameEvent_PayloadNightStarted) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mafia_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent_PayloadNightStarted.ProtoReflect.Descriptor instead.
func (*GameEvent_PayloadNightStarted) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mafia_proto_rawDescGZIP(), []int{5, 6}
}

func (x *GameEvent_PayloadNightStarted) GetDayId() uint64 {
	if x != nil {
		return x.DayId
	}
	return 0
}

func (x *GameEvent_PayloadNightStarted) GetKickedPlayer() *Player {
	if x != nil {
		return x.KickedPlayer
	}
	return nil
}

func (x *GameEvent_PayloadNightStarted) GetVotes() []*VotePaper {
	if x != nil {
		return x.Votes
	}
	return nil
}

var File_pkg_proto_mafia_proto protoreflect.FileDescriptor

var file_pkg_proto_mafia_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x66, 0x69,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x22, 0x69,
	0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61,
	0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x88, 0x01, 0x01,
	0x42, 0x07, 0x0a, 0x05, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x70, 0x0a, 0x09, 0x56, 0x6f, 0x74,
	0x65, 0x50, 0x61, 0x70, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x09, 0x63,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a,
	0x0a, 0x5f, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x57, 0x69, 0x74, 0x68, 0x52, 0x6f, 0x6c,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x1b, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x57, 0x69, 0x74, 0x68, 0x52, 0x6f, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x61, 0x66, 0x69,
	0x61, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x22, 0x2d, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x93, 0x0c, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x29,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6d,
	0x61, 0x66, 0x69, 0x61, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x5a, 0x0a, 0x15, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6a, 0x6f, 0x69, 0x6e,
	0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x48, 0x00,
	0x52, 0x13, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4a,
	0x6f, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x54, 0x0a, 0x13, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4c, 0x65, 0x66, 0x74, 0x48, 0x00, 0x52, 0x11, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x4a, 0x0a, 0x0f, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x47, 0x61, 0x6d,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x57, 0x0a, 0x14, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x47, 0x61,
	0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x12, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64,
	0x12, 0x5a, 0x0a, 0x15, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x65, 0x64, 0x48, 0x00, 0x52, 0x13, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x47, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x54, 0x0a, 0x13,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x64, 0x61, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x61, 0x66, 0x69,
	0x61, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x44, 0x61, 0x79, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52,
	0x11, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x61, 0x79, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x65, 0x64, 0x12, 0x5a, 0x0a, 0x15, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6e, 0x69,
	0x67, 0x68, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x4e, 0x69, 0x67, 0x68, 0x74,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x13, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x1a, 0x3c,
	0x0a, 0x13, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4a,
	0x6f, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x1a, 0x3a, 0x0a, 0x11,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x66,
	0x74, 0x12, 0x25, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x1a, 0x51, 0x0a, 0x0e, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x61, 0x66,
	0x69, 0x61, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x5e, 0x0a, 0x12, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65,
	0x64, 0x12, 0x27, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61,
	0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x1a, 0x65, 0x0a, 0x13, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x12, 0x25, 0x0a, 0x07, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x54, 0x65, 0x61, 0x6d,
	0x52, 0x07, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x27, 0x0a, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x61, 0x66,
	0x69, 0x61, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x1a, 0x75, 0x0a, 0x11, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x61, 0x79,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x61, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x64, 0x61, 0x79, 0x49, 0x64, 0x12, 0x37,
	0x0a, 0x0d, 0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0c, 0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x6b, 0x69, 0x6c, 0x6c,
	0x65, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x1a, 0x9f, 0x01, 0x0a, 0x13, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65,
	0x64, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x61, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x64, 0x61, 0x79, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x0d, 0x6b, 0x69, 0x63, 0x6b,
	0x65, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x00,
	0x52, 0x0c, 0x6b, 0x69, 0x63, 0x6b, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x88, 0x01,
	0x01, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x50, 0x61, 0x70,
	0x65, 0x72, 0x52, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x6b, 0x69,
	0x63, 0x6b, 0x65, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0xbd, 0x01, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x56, 0x45, 0x4e, 0x54,
	0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x4a, 0x4f, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x01,
	0x12, 0x15, 0x0a, 0x11, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52,
	0x5f, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x56, 0x45, 0x4e, 0x54,
	0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x56,
	0x45, 0x4e, 0x54, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44,
	0x10, 0x04, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x47, 0x41, 0x4d, 0x45,
	0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x05, 0x12, 0x15, 0x0a, 0x11, 0x45,
	0x56, 0x45, 0x4e, 0x54, 0x5f, 0x44, 0x41, 0x59, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44,
	0x10, 0x06, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x4e, 0x49, 0x47, 0x48,
	0x54, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x07, 0x42, 0x09, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x9b,
	0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x61, 0x66, 0x69,
	0x61, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x12, 0x21, 0x0a, 0x04, 0x73, 0x65, 0x6c, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x04,
	0x73, 0x65, 0x6c, 0x66, 0x12, 0x2a, 0x0a, 0x07, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x54, 0x65,
	0x61, 0x6d, 0x48, 0x00, 0x52, 0x07, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x88, 0x01, 0x01,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x2e, 0x0a, 0x12,
	0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x3c, 0x0a, 0x13,
	0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x29, 0x0a, 0x0b, 0x4b, 0x69,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x29, 0x0a, 0x0b, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x0e, 0x0a, 0x0c, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x2e, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x50, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1f, 0x0a, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0b, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x04, 0x74, 0x65,
	0x61, 0x6d, 0x2a, 0x4f, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x4f,
	0x4c, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d,
	0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x49, 0x4e, 0x4e, 0x4f, 0x43, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12,
	0x10, 0x0a, 0x0c, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x53, 0x48, 0x45, 0x52, 0x49, 0x46, 0x46, 0x10,
	0x02, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x4d, 0x41, 0x46, 0x49, 0x4f, 0x53,
	0x49, 0x10, 0x03, 0x2a, 0x3c, 0x0a, 0x04, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x10, 0x0a, 0x0c, 0x54,
	0x45, 0x41, 0x4d, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x0e, 0x54, 0x45, 0x41, 0x4d, 0x5f, 0x43, 0x49, 0x56, 0x49, 0x4c, 0x49, 0x41, 0x4e, 0x53, 0x10,
	0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x45, 0x41, 0x4d, 0x5f, 0x4d, 0x41, 0x46, 0x49, 0x41, 0x10,
	0x02, 0x32, 0xf3, 0x02, 0x0a, 0x05, 0x4d, 0x61, 0x66, 0x69, 0x61, 0x12, 0x36, 0x0a, 0x08, 0x4a,
	0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e,
	0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x10, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x30, 0x01, 0x12, 0x4a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x47, 0x65, 0x74,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x44, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19,
	0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x61, 0x66, 0x69,
	0x61, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x12, 0x2e,
	0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x4b, 0x69, 0x6c, 0x6c, 0x12, 0x12,
	0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x4b, 0x69, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x54, 0x65, 0x61, 0x6d, 0x12, 0x17, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x6f, 0x72, 0x6f, 0x7a, 0x68, 0x6b, 0x61, 0x61, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_mafia_proto_rawDescOnce sync.Once
	file_pkg_proto_mafia_proto_rawDescData = file_pkg_proto_mafia_proto_rawDesc
)

func file_pkg_proto_mafia_proto_rawDescGZIP() []byte {
	file_pkg_proto_mafia_proto_rawDescOnce.Do(func() {
		file_pkg_proto_mafia_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_mafia_proto_rawDescData)
	})
	return file_pkg_proto_mafia_proto_rawDescData
}

var file_pkg_proto_mafia_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_proto_mafia_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pkg_proto_mafia_proto_goTypes = []interface{}{
	(Role)(0),                             // 0: mafia.Role
	(Team)(0),                             // 1: mafia.Team
	(GameEvent_Type)(0),                   // 2: mafia.GameEvent.Type
	(*Player)(nil),                        // 3: mafia.Player
	(*VotePaper)(nil),                     // 4: mafia.VotePaper
	(*GetPlayersWithRolesRequest)(nil),    // 5: mafia.GetPlayersWithRolesRequest
	(*GetPlayersWithRolesResponse)(nil),   // 6: mafia.GetPlayersWithRolesResponse
	(*JoinGameRequest)(nil),               // 7: mafia.JoinGameRequest
	(*GameEvent)(nil),                     // 8: mafia.GameEvent
	(*GetGameStatusRequest)(nil),          // 9: mafia.GetGameStatusRequest
	(*GetGameStatusResponse)(nil),         // 10: mafia.GetGameStatusResponse
	(*SendMessageRequest)(nil),            // 11: mafia.SendMessageRequest
	(*SendMessageResponse)(nil),           // 12: mafia.SendMessageResponse
	(*KickRequest)(nil),                   // 13: mafia.KickRequest
	(*KickResponse)(nil),                  // 14: mafia.KickResponse
	(*KillRequest)(nil),                   // 15: mafia.KillRequest
	(*KillResponse)(nil),                  // 16: mafia.KillResponse
	(*CheckTeamRequest)(nil),              // 17: mafia.CheckTeamRequest
	(*CheckTeamResponse)(nil),             // 18: mafia.CheckTeamResponse
	(*GameEvent_PayloadPlayerJoined)(nil), // 19: mafia.GameEvent.PayloadPlayerJoined
	(*GameEvent_PayloadPlayerLeft)(nil),   // 20: mafia.GameEvent.PayloadPlayerLeft
	(*GameEvent_PayloadMessage)(nil),      // 21: mafia.GameEvent.PayloadMessage
	(*GameEvent_PayloadGameStarted)(nil),  // 22: mafia.GameEvent.PayloadGameStarted
	(*GameEvent_PayloadGameFinished)(nil), // 23: mafia.GameEvent.PayloadGameFinished
	(*GameEvent_PayloadDayStarted)(nil),   // 24: mafia.GameEvent.PayloadDayStarted
	(*GameEvent_PayloadNightStarted)(nil), // 25: mafia.GameEvent.PayloadNightStarted
}
var file_pkg_proto_mafia_proto_depIdxs = []int32{
	0,  // 0: mafia.Player.role:type_name -> mafia.Role
	3,  // 1: mafia.VotePaper.voter:type_name -> mafia.Player
	3,  // 2: mafia.VotePaper.candidate:type_name -> mafia.Player
	3,  // 3: mafia.GetPlayersWithRolesResponse.players:type_name -> mafia.Player
	2,  // 4: mafia.GameEvent.type:type_name -> mafia.GameEvent.Type
	19, // 5: mafia.GameEvent.payload_player_joined:type_name -> mafia.GameEvent.PayloadPlayerJoined
	20, // 6: mafia.GameEvent.payload_player_left:type_name -> mafia.GameEvent.PayloadPlayerLeft
	21, // 7: mafia.GameEvent.payload_message:type_name -> mafia.GameEvent.PayloadMessage
	22, // 8: mafia.GameEvent.payload_game_started:type_name -> mafia.GameEvent.PayloadGameStarted
	23, // 9: mafia.GameEvent.payload_game_finished:type_name -> mafia.GameEvent.PayloadGameFinished
	24, // 10: mafia.GameEvent.payload_day_started:type_name -> mafia.GameEvent.PayloadDayStarted
	25, // 11: mafia.GameEvent.payload_night_started:type_name -> mafia.GameEvent.PayloadNightStarted
	3,  // 12: mafia.GetGameStatusResponse.players:type_name -> mafia.Player
	3,  // 13: mafia.GetGameStatusResponse.self:type_name -> mafia.Player
	1,  // 14: mafia.GetGameStatusResponse.winners:type_name -> mafia.Team
	1,  // 15: mafia.CheckTeamResponse.team:type_name -> mafia.Team
	3,  // 16: mafia.GameEvent.PayloadPlayerJoined.player:type_name -> mafia.Player
	3,  // 17: mafia.GameEvent.PayloadPlayerLeft.player:type_name -> mafia.Player
	3,  // 18: mafia.GameEvent.PayloadMessage.sender:type_name -> mafia.Player
	3,  // 19: mafia.GameEvent.PayloadGameStarted.players:type_name -> mafia.Player
	0,  // 20: mafia.GameEvent.PayloadGameStarted.role:type_name -> mafia.Role
	1,  // 21: mafia.GameEvent.PayloadGameFinished.winners:type_name -> mafia.Team
	3,  // 22: mafia.GameEvent.PayloadGameFinished.players:type_name -> mafia.Player
	3,  // 23: mafia.GameEvent.PayloadDayStarted.killed_player:type_name -> mafia.Player
	3,  // 24: mafia.GameEvent.PayloadNightStarted.kicked_player:type_name -> mafia.Player
	4,  // 25: mafia.GameEvent.PayloadNightStarted.votes:type_name -> mafia.VotePaper
	7,  // 26: mafia.Mafia.JoinGame:input_type -> mafia.JoinGameRequest
	9,  // 27: mafia.Mafia.GetGameStatus:input_type -> mafia.GetGameStatusRequest
	11, // 28: mafia.Mafia.SendMessage:input_type -> mafia.SendMessageRequest
	13, // 29: mafia.Mafia.Kick:input_type -> mafia.KickRequest
	15, // 30: mafia.Mafia.Kill:input_type -> mafia.KillRequest
	17, // 31: mafia.Mafia.CheckTeam:input_type -> mafia.CheckTeamRequest
	8,  // 32: mafia.Mafia.JoinGame:output_type -> mafia.GameEvent
	10, // 33: mafia.Mafia.GetGameStatus:output_type -> mafia.GetGameStatusResponse
	12, // 34: mafia.Mafia.SendMessage:output_type -> mafia.SendMessageResponse
	14, // 35: mafia.Mafia.Kick:output_type -> mafia.KickResponse
	16, // 36: mafia.Mafia.Kill:output_type -> mafia.KillResponse
	18, // 37: mafia.Mafia.CheckTeam:output_type -> mafia.CheckTeamResponse
	32, // [32:38] is the sub-list for method output_type
	26, // [26:32] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_pkg_proto_mafia_proto_init() }
func file_pkg_proto_mafia_proto_init() {
	if File_pkg_proto_mafia_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_mafia_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VotePaper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayersWithRolesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayersWithRolesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckTeamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckTeamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameEvent_PayloadPlayerJoined); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameEvent_PayloadPlayerLeft); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameEvent_PayloadMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameEvent_PayloadGameStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameEvent_PayloadGameFinished); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameEvent_PayloadDayStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_mafia_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameEvent_PayloadNightStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_proto_mafia_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_pkg_proto_mafia_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_pkg_proto_mafia_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*GameEvent_PayloadPlayerJoined_)(nil),
		(*GameEvent_PayloadPlayerLeft_)(nil),
		(*GameEvent_PayloadMessage_)(nil),
		(*GameEvent_PayloadGameStarted_)(nil),
		(*GameEvent_PayloadGameFinished_)(nil),
		(*GameEvent_PayloadDayStarted_)(nil),
		(*GameEvent_PayloadNightStarted_)(nil),
	}
	file_pkg_proto_mafia_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_pkg_proto_mafia_proto_msgTypes[21].OneofWrappers = []interface{}{}
	file_pkg_proto_mafia_proto_msgTypes[22].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_mafia_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_mafia_proto_goTypes,
		DependencyIndexes: file_pkg_proto_mafia_proto_depIdxs,
		EnumInfos:         file_pkg_proto_mafia_proto_enumTypes,
		MessageInfos:      file_pkg_proto_mafia_proto_msgTypes,
	}.Build()
	File_pkg_proto_mafia_proto = out.File
	file_pkg_proto_mafia_proto_rawDesc = nil
	file_pkg_proto_mafia_proto_goTypes = nil
	file_pkg_proto_mafia_proto_depIdxs = nil
}
